### ISSUE TITLE
[Feature Request] IP override

### ISSUE THREAD

**Issue by thomasfinstad** [Heyter/CountryTag#1]
Would it be possible to add a config directive that would let you set the country of some IPs as an override?

It could be used to fix errors in the GeoIP database, but I would be using it for local IPs since I connect to the server from the local network I can never get the propper country to show up for myself.

Maybe something like 
`sm_countrytag_override "192.168.0.*:Germany 10.0.*.*:Poland"`
or maybe
`sm_countrytag_override "192.168.0.0/24:Germany 10.0.0.0/16:Poland"`

**Comment by Heyter** [comment]
I dont know. I do not plan to expand the functionality.
